name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git push --force https://${{ secrets.HF_TOKEN }}@huggingface.co/spaces/gulatiadiii/text_to_image main
